/* eslint-disable @next/next/no-sync-scripts */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DesktopNavbar from "../../components/navbar/DesktopNavbar";
import Footer from "../../components/footer/footer";
import { Amiri } from 'next/font/google';
import { clsx } from "clsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const amiri = Amiri({
  subsets: ['arabic'],
  variable: '--font-arabic',
  weight: ['400', '700'], // You can customize weights as needed
});

const metadataMap = {
  en: {
    title: {
      home: 'Home',
      about_Us: 'About_Us',
      contact_Us: 'Contact_Us',
      services: 'services',
    },
    description: {
      home: 'Welcome to the Central Laboratory For Testing & Monitoring Potato Production & Export.',
      about_Us: 'Learn about the Lab.',
      contact_Us: 'Get in touch with us.',
      services: 'Discover the services we offer.',
    },
  },
  ar: {
    title: {
      home: 'الرئيسية',
      about_Us: 'عن_المعهد',
      contact_Us: 'اتصل_بنا',
      services: 'الخدمات',
    },
    description: {
      home: 'مرحبًا بكم في المعمل المركزي لفحص ومراقبة انتاج وتصدير البطاطس.',
      about_Us: 'تعرف على المعمل.',
      contact_Us: 'تواصل معنا.',
      services: 'اكتشف الخدمات التي نقدمها.',
    },
  },
};

export async function  generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'ar' }];
}

export async function generateMetadata({
  params
}: {
  params: Promise<{ lang: string }>;
}) {
    const lang = (await params).lang === 'ar' ? 'ar' : 'en';

  // const lang = params.lang === 'ar' ? 'ar' : 'en';
  // const path = typeof window !== 'undefined'
    //  ? window.location.pathname.split('/')[2] || 'home'
  //   : 'home' ; 
    const path = 'home'; // You can customize based on route segment if needed

    {
    console.log('[Metadata] lang:', lang); // 🔍 confirm it's running

  return {
    title: metadataMap[lang].title[path as keyof typeof metadataMap['en']['title']],
    description: metadataMap[lang].description[path as keyof typeof metadataMap['en']['description']],
    metadataBase: new URL('https://fcri.gov.eg'), // replace with your domain
    alternates: {
      canonical: `/${lang}`,
    },
    other: {},
    // // ✅ Required structure for html tag customization
    // htmlAttributes: {
    //   lang: params.lang,
    //   dir: params.lang === 'ar' ? 'rtl' : 'ltr',
    // },
  };
}
}

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}) {
    const lang = (await params).lang;
  const dir = lang === 'ar' ? 'rtl' : 'ltr';

  return (
    <html
      lang={lang} dir={dir}
      className={clsx(
        "h-full antialiased",
      )}
    >
      {/* <body className={`min-h-full flex flex-col font-arabic`}> */}
      <body className={clsx(
        amiri.variable,
        lang === 'ar' ? 'font-arabic' : 'font-sans',  // 👈 Conditional font class
        "min-h-full flex flex-col"
      )}>
        <DesktopNavbar />
        {children}
        <Footer rtl={dir === 'rtl' ? true : false}/>
        {/* <script src="../../node_modules/preline/dist/preline.js"></script> */}
      </body>
    </html>
  );
}
